### ISSUE TITLE
TOKEN_INVALID error

### ISSUE THREAD

**Issue by DaniloL88s** [cktsun1031/discord-captcha-site#2]
I receive this error

`
Error [TOKEN_INVALID]: An invalid token was provided.
    at Client.login (/home/hydra-hosting/verification-test/node_modules/discord.js/src/client/Client.js:237:52)
    at Object.<anonymous> (/home/hydra-hosting/verification-test/index.js:11:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  [Symbol(code)]: 'TOKEN_INVALID'
`

As CLIENT_SECRET I've put the Client Secret of the BOT and as TOKEN the token of the bot. What's the error?

P.S.: I've done the `npm i` before the `npm start`

**Comment by Cloudgamer178** [comment]
Have you done the reset of token sence discord changed the token thing

**Comment by DaniloL88s** [comment]
> Have you done the reset of token sence discord changed the token thing

Yes, I've created a new one but none changed.

**Comment by CloudGamer131** [comment]
try to install one package at a time see if that works

**Comment by DaniloL88s** [comment]
It doesn't work, same error...
I use the bot on Linux

**Comment by cktsun1031** [comment]
you can add `TOKEN` in `.env`
